/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package famatese;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Accion extends javax.swing.JFrame {
    String coneccionbd = ("jdbc:sqlserver://localhost:1433;databaseName=farmacia_tese;user=sa;password=sasa");

    public Accion() {
        initComponents();
        consultarTodo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        claveA = new javax.swing.JTextField();
        accion = new javax.swing.JTextField();
        editar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        agregar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tiempoAccion = new javax.swing.JTextField();
        desc = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("ID Accion Terapeutica");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 90, 120, 16);

        jLabel2.setText("Accion Terapeutica");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 140, 120, 16);
        getContentPane().add(claveA);
        claveA.setBounds(140, 80, 90, 30);
        getContentPane().add(accion);
        accion.setBounds(140, 130, 90, 30);

        editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/famatese/7modificar.png"))); // NOI18N
        editar.setToolTipText("Modificar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        getContentPane().add(editar);
        editar.setBounds(290, 210, 60, 60);

        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/famatese/5eliminar.png"))); // NOI18N
        eliminar.setToolTipText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar);
        eliminar.setBounds(400, 210, 60, 60);

        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/famatese/4agregar.png"))); // NOI18N
        agregar.setToolTipText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar);
        agregar.setBounds(50, 210, 60, 64);

        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/famatese/2buscarr.png"))); // NOI18N
        buscar.setToolTipText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar);
        buscar.setBounds(170, 210, 60, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ACCION TERAPEUTICA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 10, 470, 20);

        jLabel4.setText("Tiempo acción");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(250, 90, 90, 16);

        jLabel5.setText("Descripción");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(260, 140, 70, 16);
        getContentPane().add(tiempoAccion);
        tiempoAccion.setBounds(350, 80, 110, 24);
        getContentPane().add(desc);
        desc.setBounds(350, 130, 110, 24);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 510, 310);

        jMenu1.setText("Exit");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Menu Principal");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(518, 374));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        if((Inicio.getPuesto().equals("Administrador"))||(Inicio.getPuesto().equals("Supervisor"))||(Inicio.getPuesto().equals("Vendedor"))){
        String buscar = accion.getText();
        Object dato[] = new Object[4];
        if (buscar.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "¿Qué accion busca?");
        } else {
            try {

                Connection con;
                con = DriverManager.getConnection(coneccionbd);
                Statement stm = con.createStatement();
                ResultSet rs = stm.executeQuery("Select * from accion where nom_a='" + buscar + "'");
                while (rs.next()) {                   
                    for (int i = 0; i < 4; i++) {
                        dato[i] = rs.getString(i + 1).toUpperCase();
                    }
                }

            } catch (Exception e) {
            }
        }
        claveA.setText((String) dato[0]);
        accion.setText((String) dato[1]);
        tiempoAccion.setText((String) dato[2]);
        desc.setText((String) dato[3]);
        } else
            JOptionPane.showMessageDialog(rootPane,"Debe iniciar sesión para poder buscar");
    }//GEN-LAST:event_buscarActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        if((Inicio.getPuesto().equals("Administrador"))||(Inicio.getPuesto().equals("Supervisor"))){
        if (claveA.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese un ID");
        } else if (accion.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese la accion");
        } else if (tiempoAccion.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese tiempo de accion");
        } else if (desc.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese descripción");
        } else if (!verificarID()) { //Si no existe el ID entra en la creaci+on
            String ClaveA, tA, aC, dS;
            ClaveA = claveA.getText();
            aC = accion.getText();
            tA = tiempoAccion.getText();
            dS = desc.getText();
            try {
                DefaultTableModel tabla = new DefaultTableModel();
                Connection con;
                con = DriverManager.getConnection(coneccionbd);
                Statement stm = con.createStatement();
                int stt = stm.executeUpdate("insert into accion values "
                        + "('" + ClaveA
                        + "','" + aC
                        + "','" + tA
                        + "','" + dS
                        + "')");
                if (stt >= 1) {
                    JOptionPane.showMessageDialog(rootPane, "Registro creado");
                    clearfields();
                    consultarTodo();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "no se  pudo crear");
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(rootPane, " No se  pudo crear");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "YA EXISTE LA CLAVE QUE INTENTA ASIGNAR", "No se puede crear", 2);
        }
        } else
            JOptionPane.showMessageDialog(rootPane,"Solo los administradores y supervisores pueden agregar, por favor inicie sesión");
    }//GEN-LAST:event_agregarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        
if(Inicio.getPuesto().equals("Administrador")){
        String clave = claveA.getText();
        if (clave.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Por favor ingrese al clave del elemento que desea eliminar");
        } else if (buscarID()) {
            int i = JOptionPane.showConfirmDialog(rootPane, "Confirma la eliminación?", "Eliminar elemento", 2, 2);
            if (i <= 0) {
                try {
                    Connection con;
                    con = DriverManager.getConnection(coneccionbd);
                    Statement stm = con.createStatement();
                    stm.executeUpdate("delete from accion where cod_a='" + clave + "'");
                } catch (Exception e) {
                    e.printStackTrace();
                }
                consultarTodo();
            }
        } else 
            JOptionPane.showMessageDialog(rootPane, ("No existe: " + clave));
        } else
            JOptionPane.showMessageDialog(rootPane,"Solo los administradores pueden eliminar");
    }//GEN-LAST:event_eliminarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setVisible(false);
        Inicio obj = new Inicio();
        obj.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        
if(Inicio.getPuesto().equals("Administrador")){
        if (!(claveA.getText().equals(""))) {
            System.out.println("paso1");
            if (verificarID() || !(accion.getText().equals("") || tiempoAccion.getText().equals("") || desc.getText().equals(""))) {
                System.out.println("paso2");
                String actualizar = "Accion terapeutica= '" + accion.getText() + "' \n"
                        + "Tipo de acción= '" + tiempoAccion.getText() + "'\n"
                        + "Descripción= '" + desc.getText() + "'";
                int procd = JOptionPane.showConfirmDialog(rootPane, actualizar, ("Se actualizara la informacion para: " + claveA.getText()), 2, 2);
                System.out.println(procd);
                if (procd <= 0) {
                    try {
                        Connection con = DriverManager.getConnection(coneccionbd);
                        Statement stm = con.createStatement();
                        int act = stm.executeUpdate("update accion set "
                                + "nom_a='" + accion.getText() + "',"
                                + "tie_a='" + tiempoAccion.getText() + "',"
                                + "des_a='" + desc.getText() + "'"
                                + "where cod_a='" + claveA.getText() + "'");
                        if (act >= 1) {
                            JOptionPane.showMessageDialog(rootPane, "Actualizado");
                            consultarTodo();
                            clearfields();
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "no se puede actualizar");
                        }
                    } catch (SQLException e) {
                        e.printStackTrace();
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, ("No se encontro el id: " + claveA.getText()));
            consultarTodo();
            clearfields();
        }
        System.out.println("paso0");
        } else
            JOptionPane.showMessageDialog(rootPane, "Solo el administrador puede editar");

    }//GEN-LAST:event_editarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accion().setVisible(true);
            }
        });
    }

    //Grunditses:
    private void clearfields() {
        claveA.setText("");
        accion.setText("");
        tiempoAccion.setText("");
        desc.setText("");
    }

    private boolean verificarID() {
        String buscar = claveA.getText();
        try {
            Connection con;
            con = DriverManager.getConnection(coneccionbd);
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("Select * from accion where cad_a='" + buscar + "'");
            while (rs.next()) {
                claveA.setText(String.valueOf(rs.getString(1)));
                return true;
            }

        } catch (Exception e) {
        }
        return false; //si no encontro nada falso

    }

    private void consultarTodo() {
        try {
            DefaultTableModel tabla = new DefaultTableModel();
            Connection con;
            con = DriverManager.getConnection(coneccionbd);
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("Select * from accion");
            tabla.addColumn("ID Accion");
            tabla.addColumn("Tipo de accion");
            tabla.addColumn("Teimpo de accion");
            tabla.addColumn("Descripcion");
            while (rs.next()) {
                Object dato[] = new Object[4];
                for (int i = 0; i < 4; i++) {
                    //convertir a mayusculas del lado de la app
                    dato[i] = rs.getString(i + 1).toUpperCase();
                }
                tabla.addRow(dato);
            }
       
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private boolean buscarID() {
        String buscar = claveA.getText();
        try {
            Connection con;
            con = DriverManager.getConnection(coneccionbd);
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("Select * from accion where cod_a='" + buscar + "'");
            while (rs.next()) {
                claveA.setText(String.valueOf(rs.getString(1)));
                return true;
            }

        } catch (Exception e) {
        }
        return false; //si no encontro nada falso
    }
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accion;
    private javax.swing.JButton agregar;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField claveA;
    private javax.swing.JTextField desc;
    private javax.swing.JButton editar;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tiempoAccion;
    // End of variables declaration//GEN-END:variables
}
