/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package famatese;

import com.sun.glass.events.KeyEvent;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;



public class Contraseña extends javax.swing.JFrame {
    String coneccionbd = ("jdbc:sqlserver://localhost:1433;databaseName=farmacia_tese;user=sa;password=sasa");
    private boolean admon = false;
    /**
     * Creates new form Contraseña
     */
    public Contraseña() {
        admon = false;
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        psw = new javax.swing.JPasswordField();
        inicioSesion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 304, 56, 20);

        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 340, 70, 16);
        getContentPane().add(usuario);
        usuario.setBounds(110, 290, 232, 30);

        psw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pswKeyPressed(evt);
            }
        });
        getContentPane().add(psw);
        psw.setBounds(110, 330, 232, 30);

        inicioSesion.setText("Iniciar Sesión");
        inicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioSesionActionPerformed(evt);
            }
        });
        getContentPane().add(inicioSesion);
        inicioSesion.setBounds(150, 380, 110, 32);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("FARMATECMX S.A. DE C.V.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 7, 400, 40);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(null);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/presentacion-farmacia.png"))); // NOI18N
        jPanel1.add(jButton3);
        jButton3.setBounds(120, 130, 220, 170);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo-Farmacia-BandadoRio.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 60, 220, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, -20, 410, 460);
        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(416, 480));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    //BOTON PARA ENTRAR
    private void inicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioSesionActionPerformed
       login();
    }//GEN-LAST:event_inicioSesionActionPerformed

    private void pswKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            login();
        }
    }//GEN-LAST:event_pswKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inicioSesion;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField psw;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables

//PARA PODER IMPLEMENTAR EL ENTER EN EL CAMPO CONTRASEÑA, Y EVITAR DAR CLICK AL BOTON ENTRAR
private void login(){
     if (String.valueOf(usuario.getText()).compareTo("") == 0 && String.valueOf(psw.getPassword()).compareTo("") == 0) {
            JOptionPane.showMessageDialog(null, "INGRESE UN USUARIO Y UNA CONTRASEÑA");
        } else {
            if (String.valueOf(usuario.getText()).compareTo(usuario.getText()) == 0 && String.valueOf(psw.getPassword()).compareTo("") == 0) {
                JOptionPane.showMessageDialog(null, "INGRESE UNA CONTRASEÑA");
            } else {
                if (String.valueOf(usuario.getText()).compareTo("") == 0 && String.valueOf(psw.getPassword()).compareTo(psw.getText()) == 0) {
                    JOptionPane.showMessageDialog(null, "INGRESE UN USUARIO");
                } else { //inicio de comparacion
                    boolean entrar=findUser();
                    if (entrar) {
                        this.setVisible(false);
                        Inicio obj = new Inicio(admon);
                        obj.show();
                        JOptionPane.showMessageDialog(null, "BIENVENIDO AL SISTEMA");
                       // Si logra entrar System.out.println(entrar);
                       // Si es admon System.out.println(admon);
                    } else {
                        JOptionPane.showMessageDialog(null, "USUARIO O CONTRASEÑA INCORRECTOS");
                    }
                }//fin else de comparacion
            }
        }
                        // Admon en false por default System.out.println(admon);
}

private boolean findUser() {
        String user = usuario.getText();
        String pass = psw.getText();
        try {
            Connection con;
            con = DriverManager.getConnection(coneccionbd);
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("Select admon from users where user_u='" + user + "' and psw='"+pass+"'");
            while (rs.next()) {
                admon=rs.getBoolean(1);
                return true;
            }

        } catch (Exception e) {
        }
        return false; //si no encontro nada falso

    }
}
