/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package famatese;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Empleado extends javax.swing.JFrame {

   String coneccionbd = ("jdbc:sqlserver://localhost:1433;databaseName=FARMATEC2;user=sa;password=sasa");
    public Empleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        claveemp = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        ap = new javax.swing.JTextField();
        am = new javax.swing.JTextField();
        fecha = new javax.swing.JTextField();
        idci = new javax.swing.JTextField();
        idco = new javax.swing.JTextField();
        idca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("ID Empleado");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 50, 80, 30);

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 90, 80, 20);

        jLabel3.setText("Apellido Paterno");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 120, 100, 40);

        jLabel4.setText("Apellido Materno");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 170, 100, 20);

        jLabel5.setText("Fecha Nacimiento");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(350, 50, 100, 20);

        jLabel7.setText("fnac");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(350, 80, 70, 30);

        jLabel8.setText("enfer");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(350, 130, 70, 20);

        jLabel9.setText("cod farmac");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(350, 170, 70, 20);

        claveemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveempActionPerformed(evt);
            }
        });
        getContentPane().add(claveemp);
        claveemp.setBounds(150, 40, 133, 30);
        getContentPane().add(nombre);
        nombre.setBounds(150, 80, 133, 30);
        getContentPane().add(ap);
        ap.setBounds(150, 120, 133, 30);
        getContentPane().add(am);
        am.setBounds(150, 160, 133, 30);
        getContentPane().add(fecha);
        fecha.setBounds(460, 40, 133, 30);

        idci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idciActionPerformed(evt);
            }
        });
        getContentPane().add(idci);
        idci.setBounds(460, 80, 130, 30);
        getContentPane().add(idco);
        idco.setBounds(460, 120, 130, 30);
        getContentPane().add(idca);
        idca.setBounds(460, 160, 130, 30);

        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 250, 650, 103);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/7modificar.png"))); // NOI18N
        jButton11.setToolTipText("Modificar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(40, 370, 44, 39);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/5eliminar.png"))); // NOI18N
        jButton13.setToolTipText("Eliminar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(230, 370, 44, 39);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/4agregar.png"))); // NOI18N
        jButton14.setToolTipText("Agregar");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(320, 370, 44, 39);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/3consultar.png"))); // NOI18N
        jButton15.setToolTipText("Consultar");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(420, 370, 44, 39);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/2buscarr.png"))); // NOI18N
        jButton16.setToolTipText("Buscar");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16);
        jButton16.setBounds(520, 370, 44, 39);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("EMPLEADO");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 670, 30);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 240, 720, 190);

        jMenu1.setText("Busqueda Avanzada");

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem8.setText("Avanzada");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenu3.setText("Buscar por ");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Puesto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Ciudad");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setText("Colonia");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setText("Calle");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem5.setText("Horario");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Consulta Avanzada");

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem9.setText("Avanzada");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Exit");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem6.setText("Menu Principal");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem7.setText("Salir");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(687, 487));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idciActionPerformed

    private void claveempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claveempActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
         String clave;
        clave=claveemp.getText();
        try {
            DefaultTableModel tabla = new DefaultTableModel();
            Connection con;
            con = DriverManager.getConnection(coneccionbd);
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("Select * from Empleado where ID_Emp='"+clave+"'");
            tabla.addColumn("ID Empleado");
            tabla.addColumn("Nombre");
            tabla.addColumn("Apellido Paterno");
            tabla.addColumn("Apellido materno");
            tabla.addColumn("Fecha Nacimiento");
            tabla.addColumn("ID Puesto");
            tabla.addColumn("ID Ciudad");
            tabla.addColumn("ID Colonia");
            tabla.addColumn("ID Calle");
            tabla.addColumn("ID Horario");
            while (rs.next()) {
                Object dato[] = new Object[10];
                for (int i = 0; i < 10; i++) {
                    dato[i] = rs.getString(i + 1);
                }
                tabla.addRow(dato);
            }
            this.Tabla1.setModel(tabla);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
         try {
            DefaultTableModel tabla = new DefaultTableModel();
            Connection con;
            con = DriverManager.getConnection(coneccionbd);
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("Select * from Empleado");
            tabla.addColumn("ID Empleado");
            tabla.addColumn("Nombre");
            tabla.addColumn("Apellido Paterno");
            tabla.addColumn("Apellido materno");
            tabla.addColumn("Fecha Nacimiento");
            tabla.addColumn("ID Puesto");
            tabla.addColumn("ID Ciudad");
            tabla.addColumn("ID Colonia");
            tabla.addColumn("ID Calle");
            tabla.addColumn("ID Horario");
            while (rs.next()) {
                Object dato[] = new Object[10];
                for (int i = 0; i < 10; i++) {
                    dato[i] = rs.getString(i + 1);
                }
                tabla.addRow(dato);
            }
            this.Tabla1.setModel(tabla);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
       if(claveemp.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Ingrese un ID");
        }
        if(nombre.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Ingrese el nombre");
        }
        if(ap.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Ingrese el apellido paterno");
        }
        if(am.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Ingrese el apellido materno");
        }
        if(fecha.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Ingrese la fecha");
        }
        if(idci.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Ingrese el id de la ciudad");
        }
        if(idco.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Ingrese el id de la colonia");
        }
        if(idca.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Ingrese el id de la calle");
        }
        String Claveemp,Nombre,Ap,Am,Fecha,Idci,Idp,Idco,Idca,Idho ;
        Claveemp=claveemp.getText();
        Nombre=nombre.getText();
        Ap=ap.getText();
        Am=am.getText();
        Fecha=fecha.getText();
        Idci=idci.getText();
        Idco=idco.getText();
        Idca=idca.getText();
        try {
            DefaultTableModel tabla = new DefaultTableModel();
            Connection con;
            con = DriverManager.getConnection(coneccionbd);
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("insert into Empleado values ('"+Claveemp+"','"+Nombre+"','"+Ap+"','"+Am+"','"+Fecha+"','"+"','"+Idci+"','"+Idco+"','"+Idca+"','"+"')");
        } catch (Exception e) {
        }        
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
       String clave;
        clave=claveemp.getText();
        try {
            DefaultTableModel tabla = new DefaultTableModel();
            Connection con;
            con = DriverManager.getConnection(coneccionbd);
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("delete from Empleado where ID_Emp='"+clave+"'");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       String clave;
        clave=idca.getText();
        try {
            DefaultTableModel tabla = new DefaultTableModel();
            Connection con;
            con = DriverManager.getConnection(coneccionbd);
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("Select * from Empleado INNER JOIN Calle ON ID_Calle2=ID_Calle where ID_Calle='"+clave+"'");
            tabla.addColumn("ID Empleado");
            tabla.addColumn("Nombre");
            tabla.addColumn("Apellido Paterno");
            tabla.addColumn("Apellido materno");
            tabla.addColumn("Fecha Nacimiento");
            tabla.addColumn("ID Puesto");
            tabla.addColumn("ID Ciudad");
            tabla.addColumn("ID Colonia");
            tabla.addColumn("ID Calle");
            tabla.addColumn("ID Horario");
            while (rs.next()) {
                Object dato[] = new Object[10];
                for (int i = 0; i < 10; i++) {
                    dato[i] = rs.getString(i + 1);
                }
                tabla.addRow(dato);
            }
            this.Tabla1.setModel(tabla);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String clave;
        try {
            DefaultTableModel tabla = new DefaultTableModel();
            Connection con;
            con = DriverManager.getConnection(coneccionbd);
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("Select * from Empleado INNER JOIN Puesto ON ID_Puesto1=ID_Puesto where ID_Puesto='"+"'");
            tabla.addColumn("ID Empleado");
            tabla.addColumn("Nombre");
            tabla.addColumn("Apellido Paterno");
            tabla.addColumn("Apellido materno");
            tabla.addColumn("Fecha Nacimiento");
            tabla.addColumn("ID Puesto");
            tabla.addColumn("ID Ciudad");
            tabla.addColumn("ID Colonia");
            tabla.addColumn("ID Calle");
            tabla.addColumn("ID Horario");
            while (rs.next()) {
                Object dato[] = new Object[10];
                for (int i = 0; i < 10; i++) {
                    dato[i] = rs.getString(i + 1);
                }
                tabla.addRow(dato);
            }
            this.Tabla1.setModel(tabla);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
          String clave;
        clave=idci.getText();
        try {
            DefaultTableModel tabla = new DefaultTableModel();
            Connection con;
            con = DriverManager.getConnection(coneccionbd);
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("Select * from Empleado INNER JOIN Ciudad ON ID_Ciu2=ID_Ciu where ID_Ciu='"+clave+"'");
            tabla.addColumn("ID Empleado");
            tabla.addColumn("Nombre");
            tabla.addColumn("Apellido Paterno");
            tabla.addColumn("Apellido materno");
            tabla.addColumn("Fecha Nacimiento");
            tabla.addColumn("ID Puesto");
            tabla.addColumn("ID Ciudad");
            tabla.addColumn("ID Colonia");
            tabla.addColumn("ID Calle");
            tabla.addColumn("ID Horario");
            while (rs.next()) {
                Object dato[] = new Object[10];
                for (int i = 0; i < 10; i++) {
                    dato[i] = rs.getString(i + 1);
                }
                tabla.addRow(dato);
            }
            this.Tabla1.setModel(tabla);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
          String clave;
        clave=idco.getText();
        try {
            DefaultTableModel tabla = new DefaultTableModel();
            Connection con;
            con = DriverManager.getConnection(coneccionbd);
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("Select * from Empleado INNER JOIN Colonia ON ID_Col2=ID_Col where ID_Col='"+clave+"'");
            tabla.addColumn("ID Empleado");
            tabla.addColumn("Nombre");
            tabla.addColumn("Apellido Paterno");
            tabla.addColumn("Apellido materno");
            tabla.addColumn("Fecha Nacimiento");
            tabla.addColumn("ID Puesto");
            tabla.addColumn("ID Ciudad");
            tabla.addColumn("ID Colonia");
            tabla.addColumn("ID Calle");
            tabla.addColumn("ID Horario");
            while (rs.next()) {
                Object dato[] = new Object[10];
                for (int i = 0; i < 10; i++) {
                    dato[i] = rs.getString(i + 1);
                }
                tabla.addRow(dato);
            }
            this.Tabla1.setModel(tabla);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
    String clave;
       
        try {
            DefaultTableModel tabla = new DefaultTableModel();
            Connection con;
            con = DriverManager.getConnection(coneccionbd);
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("Select * from Empleado INNER JOIN Horario ON ID_Horario2=ID_Horario where ID_Horario='"+"'");
            tabla.addColumn("ID Empleado");
            tabla.addColumn("Nombre");
            tabla.addColumn("Apellido Paterno");
            tabla.addColumn("Apellido materno");
            tabla.addColumn("Fecha Nacimiento");
            tabla.addColumn("ID Puesto");
            tabla.addColumn("ID Ciudad");
            tabla.addColumn("ID Colonia");
            tabla.addColumn("ID Calle");
            tabla.addColumn("ID Horario");
            while (rs.next()) {
                Object dato[] = new Object[10];
                for (int i = 0; i < 10; i++) {
                    dato[i] = rs.getString(i + 1);
                }
                tabla.addRow(dato);
            }
            this.Tabla1.setModel(tabla);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    //Ir a inicio
    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        this.setVisible(false);
        Inicio obj = new Inicio();
        obj.show();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    //salir programa
    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    
    
    //Buscar empleado por id
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
      try {
         String Claveemp;
         Claveemp=claveemp.getText();
            Connection con;
            con = DriverManager.getConnection(coneccionbd);
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("select * from Empleado where ID_Emp='" +Claveemp + "'");
           if(rs.next()){
               claveemp.setText(String.valueOf(rs.getString(1)));
               nombre.setText(String.valueOf(rs.getString(2)));
               ap.setText(String.valueOf(rs.getString(3)));
               am.setText(String.valueOf(rs.getString(4)));
               fecha.setText(String.valueOf(rs.getString(5)));
    
               idci.setText(String.valueOf(rs.getString(7)));
               idco.setText(String.valueOf(rs.getString(8)));
               idca.setText(String.valueOf(rs.getString(9)));
               
               
               claveemp.setEnabled(false);
               nombre.setEnabled(true);
               ap.setEnabled(true);
               am.setEnabled(true);
               fecha.setEnabled(true);
          
               idci.setEnabled(true);
               idco.setEnabled(true);
               idca.setEnabled(true);
            
               
               stm.close();
           }
        } catch (SQLException e) {
          
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
         try {
            DefaultTableModel tabla = new DefaultTableModel();
            Connection con;
            con = DriverManager.getConnection(coneccionbd);
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("SELECT ID_Emp,Nom_Emp,AP_Emp,AM_Emp,Fecha_Nac,Nom_Puesto,Nom_Ciu,Nom_Col,Nom_Calle,Tipo_Horario,NumTelf,Tipo_Telf\n" +
"FROM Empleado INNER JOIN TelfEMple ON ID_Emp=ID_Emp1 INNER JOIN TipoTelf ON ID_Telf1=ID_Telf INNER JOIN Puesto ON ID_Puesto1=ID_Puesto "
                    + "INNER JOIN Ciudad ON ID_Ciu2=ID_Ciu INNER JOIN Colonia ON ID_Col2=ID_Col\n" +
"INNER JOIN Calle ON ID_Calle2=ID_Calle INNER JOIN Horario ON ID_Horario2=ID_Horario");
            tabla.addColumn("ID Empleado");
            tabla.addColumn("Nombre Empleado");
            tabla.addColumn("Apellido Paterno");
            tabla.addColumn("Apellido Materno");
            tabla.addColumn("Fecha Nacimiento");
            tabla.addColumn("Puesto");
            tabla.addColumn("Ciudad");
            tabla.addColumn("Colonia");
            tabla.addColumn("Calle");
            tabla.addColumn("Horario");
            tabla.addColumn("Numero Telefono");
            tabla.addColumn("Tipo Telefono");
            while (rs.next()) {
                Object dato[] = new Object[12];
                for (int i = 0; i < 12; i++) {
                    dato[i] = rs.getString(i + 1);
                }
                tabla.addRow(dato);
            }
            this.Tabla1.setModel(tabla);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        try {
            String clave;
            clave=claveemp.getText();
            DefaultTableModel tabla = new DefaultTableModel();
            Connection con;
            con = DriverManager.getConnection(coneccionbd);
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("SELECT ID_Emp,Nom_Emp,AP_Emp,AM_Emp,Fecha_Nac,Nom_Puesto,Nom_Ciu,Nom_Col,Nom_Calle,Tipo_Horario,NumTelf,Tipo_Telf\n" +
"FROM Empleado INNER JOIN TelfEMple ON ID_Emp=ID_Emp1 INNER JOIN TipoTelf ON ID_Telf1=ID_Telf INNER JOIN Puesto ON ID_Puesto1=ID_Puesto INNER JOIN Ciudad ON ID_Ciu2=ID_Ciu INNER JOIN Colonia ON ID_Col2=ID_Col\n" +
"INNER JOIN Calle ON ID_Calle2=ID_Calle INNER JOIN Horario ON ID_Horario2=ID_Horario\n"
                    + "where ID_Emp='"+clave+"'");
            tabla.addColumn("ID Empleado");
            tabla.addColumn("Nombre Empleado");
            tabla.addColumn("Apellido Paterno");
            tabla.addColumn("Apellido Materno");
            tabla.addColumn("Fecha Nacimiento");
            tabla.addColumn("Puesto");
            tabla.addColumn("Ciudad");
            tabla.addColumn("Colonia");
            tabla.addColumn("Calle");
            tabla.addColumn("Horario");
            tabla.addColumn("Numero Telefono");
            tabla.addColumn("Tipo Telefono");
            while (rs.next()) {
                Object dato[] = new Object[12];
                for (int i = 0; i < 12; i++) {
                    dato[i] = rs.getString(i + 1);
                }
                tabla.addRow(dato);
            }
            this.Tabla1.setModel(tabla);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla1;
    private javax.swing.JTextField am;
    private javax.swing.JTextField ap;
    private javax.swing.JTextField claveemp;
    private javax.swing.JTextField fecha;
    private javax.swing.JTextField idca;
    private javax.swing.JTextField idci;
    private javax.swing.JTextField idco;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
