/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package famatese;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Empleado extends javax.swing.JFrame {

    String coneccionbd = ("jdbc:sqlserver://localhost:1433;databaseName=farmacia_tese;user=sa;password=sasa");
    ArrayList<String> listaFarmacias = new ArrayList<>();

    public Empleado() {
        initComponents();
        consultarTodo();
        actualizarList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        claveE = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        ap = new javax.swing.JTextField();
        am = new javax.swing.JTextField();
        fn = new javax.swing.JTextField();
        fi = new javax.swing.JTextField();
        enf = new javax.swing.JTextField();
        editar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        agregar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        boxFarmacia = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("ID Empleado");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 50, 80, 30);

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 50, 80, 20);

        jLabel3.setText("Apellido Paterno");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 80, 100, 40);

        jLabel4.setText("Apellido Materno");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(330, 90, 100, 20);

        jLabel7.setText("Fecha Nac");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 120, 70, 30);

        jLabel8.setText("fechaInicio");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(350, 130, 80, 20);

        jLabel9.setText("Enfermedades?");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 170, 70, 20);

        claveE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveEActionPerformed(evt);
            }
        });
        getContentPane().add(claveE);
        claveE.setBounds(150, 40, 133, 30);
        getContentPane().add(nombre);
        nombre.setBounds(460, 40, 133, 30);
        getContentPane().add(ap);
        ap.setBounds(150, 80, 133, 30);
        getContentPane().add(am);
        am.setBounds(460, 80, 133, 30);

        fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnActionPerformed(evt);
            }
        });
        getContentPane().add(fn);
        fn.setBounds(150, 120, 130, 30);
        getContentPane().add(fi);
        fi.setBounds(460, 120, 130, 30);
        getContentPane().add(enf);
        enf.setBounds(150, 160, 130, 30);

        editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/7modificar.png"))); // NOI18N
        editar.setToolTipText("Modificar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        getContentPane().add(editar);
        editar.setBounds(340, 230, 90, 60);

        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/5eliminar.png"))); // NOI18N
        eliminar.setToolTipText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar);
        eliminar.setBounds(440, 230, 90, 60);

        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/4agregar.png"))); // NOI18N
        agregar.setToolTipText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar);
        agregar.setBounds(140, 230, 90, 60);

        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/2buscarr.png"))); // NOI18N
        buscar.setToolTipText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar);
        buscar.setBounds(240, 230, 90, 60);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("EMPLEADO");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 670, 30);

        jLabel6.setText("Farmacia");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(360, 170, 70, 20);

        boxFarmacia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(boxFarmacia);
        boxFarmacia.setBounds(460, 170, 130, 30);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 0, 690, 320);

        jMenu2.setText("Exit");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem6.setText("Menu Principal");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem7.setText("Salir");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(687, 381));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnActionPerformed

    private void claveEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claveEActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        Object dato[] = new Object[8];
        String clave = nombre.getText();
        if (clave.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese un nombre para buscar");
        } else {
            try {
                DefaultTableModel tabla = new DefaultTableModel();
                Connection con;
                con = DriverManager.getConnection(coneccionbd);
                Statement stm = con.createStatement();
                ResultSet rs = stm.executeQuery("Select * from empleado where nom_e='" + clave + "'");
          tabla.addColumn("Id Empleado");
            tabla.addColumn("Nombre");
            tabla.addColumn("A. paterno");
            tabla.addColumn("A. materno");
            tabla.addColumn("F. Nac.");
            tabla.addColumn("F. Ingreso");
            tabla.addColumn("¿Enfermedad?");
            tabla.addColumn("Farmacia");
                while (rs.next()) {
                    
                    for (int i = 0; i <8; i++) {
                        dato[i] = rs.getString(i + 1).toUpperCase();
                    }
                    tabla.addRow(dato);
                }

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(rootPane, "No se encontraron resultados");
            }
        }
        claveE.setText((String)dato[0]);
        nombre.setText((String)dato[1]);
        ap.setText((String)dato[2]);
        am.setText((String)dato[3]);
        fn.setText((String)dato[4]);
        fi.setText((String)dato[5]);
        enf.setText((String)dato[6]);
        String compararFarma = (String) dato[7];
        boxFarmacia.setSelectedIndex((listaFarmacias.indexOf(compararFarma)) / 2);
        System.out.println(((listaFarmacias.indexOf(compararFarma)) / 2));
    }//GEN-LAST:event_buscarActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        if(Inicio.getAdmon()){
        if (claveE.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese un ID de empleado");
        } else if (nombre.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese la nombre");
        } else if (ap.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese el apellido paterno");
        } else if (am.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese el apellido materno");
        } else if (fn.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese fecha de nacimiento");
        } else if (fi.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese fecha de inicio");
        } else if (enf.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "¿Padece enfermedad?");
        } else if (!verificarID()) { //Si no existe el ID entra en la creaci+on
            String cE = claveE.getText();                               
            String n = nombre.getText();
            String aP = ap.getText();
            String aM = am.getText();
            String fN= fn.getText();
            String fI= fi.getText();
            String E= enf.getText();
            int idFarmaceutico = (boxFarmacia.getSelectedIndex() * 2);
            String farma = (String) listaFarmacias.get(idFarmaceutico);  
            try {
                DefaultTableModel tabla = new DefaultTableModel();
                Connection con;
                con = DriverManager.getConnection(coneccionbd);
                Statement stm = con.createStatement();
                ResultSet rs = stm.executeQuery("insert into empleado values ('" + cE + "','"
                        + n + "','"
                        + aP + "','"
                        + aM + "','"
                        + fN + "','"
                        + fI + "','"
                        + E + "','"
                        + farma + "')");
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(rootPane, "No se pudo crear", "Compruebe los datos", 2);
            }
        }
        consultarTodo();
        clearfields();
        } else
            JOptionPane.showMessageDialog(rootPane,"No eres administrador");
    }//GEN-LAST:event_agregarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        if(Inicio.getAdmon()){
        String clave;
        clave = claveE.getText();
        int idLabo = (boxFarmacia.getSelectedIndex() * 2);
      
        String farma = (String) listaFarmacias.get(idLabo);
   
        String eliminar = "Empleado= '" + nombre.getText()+ "' \n"
                + "Apellido paterno= '" + ap.getText() + "'\n"
                + "Apellido materno= '" + am.getText() + "'\n"
                + "Fecha de nacimiento= '" + fn.getText() + "'\n"
                + "Fecha de inicio= '" + fi.getText() + "'\n"
                + "Enfermedad= '" + enf.getText() + "'\n"
                + "Farmacia = '" + farma+ "'";
        int procd = JOptionPane.showConfirmDialog(rootPane, eliminar, ("Se eliminara la informacion para: " + claveE.getText()), 2, 2);
        System.out.println(procd);
        if (procd <= 0) {
            try {
                DefaultTableModel tabla = new DefaultTableModel();
                Connection con;
                con = DriverManager.getConnection(coneccionbd);
                Statement stm = con.createStatement();
                int act = stm.executeUpdate("delete from empleado where cod_e='" + clave + "'");
                if (act >= 1) {
                            JOptionPane.showMessageDialog(rootPane, "Eliminado");
                            consultarTodo();
                            clearfields();
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "no se puede eliminar");
                        }
                
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        } else JOptionPane.showMessageDialog(rootPane,"No eres administrador");
    }//GEN-LAST:event_eliminarActionPerformed

    //Ir a inicio
    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        this.setVisible(false);
        Inicio obj = new Inicio();
        obj.show();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    //salir programa
    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    //Buscar empleado por id
    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        if(Inicio.getAdmon()){
        if (!(claveE.getText().equals(""))) {
            System.out.println("paso 1 no esta vacia la clave");
            if (verificarID()) {
                System.out.println("paso2");
                // listaLabos;
                int idLabo = (boxFarmacia.getSelectedIndex() * 2);               
                String farma = (String) listaFarmacias.get(idLabo);     
                String actualizar = "Nombre= '" + nombre.getText() + "' \n"
                        + "Apellido paterno= '" + ap.getText() + "'\n"
                        + "Apellido materno= '" + am.getText() + "'\n"
                        + "Fecha de nacimiento= '" + fn.getText() + "'\n"                        
                        + "Fecha de inicio= '" + fi.getText() + "'\n"                        
                        + "¿Enfermedad?= '" + enf.getText() + "'\n"                                                
                        + "Farmacia= '" + farma + "'";
                int procd = JOptionPane.showConfirmDialog(rootPane, actualizar, ("Se actualizara la informacion para: " + claveE.getText()), 2, 2);
                System.out.println(procd);
                if (procd <= 0) {
                    try {
                        Connection con = DriverManager.getConnection(coneccionbd);
                        Statement stm = con.createStatement();
                        int act = stm.executeUpdate("update empleado set "
                                + "nom_e='" + nombre.getText() + "',"
                                + "app_e='" + ap.getText() + "',"
                                + "apm_e='" + am.getText() + "',"
                                + "fna_e='" + fn.getText() + "',"
                                + "fin_e='" + fi.getText() + "',"
                                + "enf_e='" + enf.getText() + "',"                              
                                + "codf_1='" + farma + "'"
                                + "where cod_f='" + claveE.getText() + "'");
                        if (act >= 1) {
                            JOptionPane.showMessageDialog(rootPane, "Actualizado");
                            consultarTodo();
                            clearfields();
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "no se puede actualizar");
                        }
                    } catch (SQLException e) {
                        e.printStackTrace();
                    }
                }
            }
        }
        } else 
            JOptionPane.showMessageDialog(rootPane,"No eres administrador");
    }//GEN-LAST:event_editarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleado().setVisible(true);
            }
        });
    }

    /*----------------------------------------------------------------------------------------------------------------*/
 /*----------------------------------------------------------------------------------------------------------------*/
    //MY METHOD´S 
    //Consultar tabla, usando views en DB 
    private void consultarTodo() {
        try {
            DefaultTableModel tabla = new DefaultTableModel();
            Connection con;
            con = DriverManager.getConnection(coneccionbd);
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("Select * from empleado");
            tabla.addColumn("Id Empleado");
            tabla.addColumn("Nombre");
            tabla.addColumn("A. paterno");
            tabla.addColumn("A. materno");
            tabla.addColumn("F. Nac.");
            tabla.addColumn("F. Ingreso");
            tabla.addColumn("¿Enfermedad?");
            tabla.addColumn("Farmacia");
            while (rs.next()) {
                Object dato[] = new Object[8];
                for (int i = 0; i < 8; i++) {
                    dato[i] = rs.getString(i + 1).toUpperCase();
                }
                tabla.addRow(dato);
            }
         
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    //Actualizar cajas
    private void actualizarList() {
        boxFarmacia.removeAllItems();

        listaFarmacias = farmacias();
        //ciclo del arreglo, recorriendo posiciones par para obtener el nombre, las
        //claves pertenecen a las posiciones non
        for (int i = 1; i < listaFarmacias.size(); i += 2) {
            boxFarmacia.addItem(listaFarmacias.get(i));
            //  System.out.println(listaFarmaceuticos.get(i - 1));
        }

    }

    //Caja labos
    public ArrayList<String> farmacias() {
        ArrayList<String> farmacias = new ArrayList<>();
        try {
            Connection con = DriverManager.getConnection(coneccionbd);
            Statement stm = con.createStatement();
            String q = "select cod_f,nom_f from farmacia";
            ResultSet res = stm.executeQuery(q);
            while (res.next()) {

                Object dato[] = new Object[2];
                for (int i = 0; i < 2; i++) {
                    dato[i] = res.getString(i + 1).toUpperCase();
                    farmacias.add((String) dato[i]);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return farmacias;
    }

    //Limpiar campos
    public void clearfields() {
        claveE.setText("");
        nombre.setText("");
        ap.setText("");
        am.setText("");
        fn.setText("");
        fi.setText("");
        enf.setText("");
        boxFarmacia.setSelectedIndex(0);

    }

    //verificarID
    private boolean verificarID() {
        String buscar = claveE.getText();
        try {
            Connection con;
            con = DriverManager.getConnection(coneccionbd);
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("Select * from empleado where cod_e='" + buscar + "'");
            while (rs.next()) {
                claveE.setText(String.valueOf(rs.getString(1)));
                return true;
            }

        } catch (Exception e) {
        }
        return false; //si no encontro nada falso

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JTextField am;
    private javax.swing.JTextField ap;
    private javax.swing.JComboBox<String> boxFarmacia;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField claveE;
    private javax.swing.JButton editar;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField enf;
    private javax.swing.JTextField fi;
    private javax.swing.JTextField fn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
